[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "pmv_games"
version = "0.1.0"
description = ""
authors = [{ name = "", email = "" }]
license = { text = "" }
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "gym==0.26.2",
    "tensorboard>=2.19.0",
    "transformers>=4.51.3",
    "torch>=2.7.1"
]
